// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class WindowApiPigeonCodecReader: FlutterStandardReader {
}

private class WindowApiPigeonCodecWriter: FlutterStandardWriter {
}

private class WindowApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return WindowApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return WindowApiPigeonCodecWriter(data: data)
  }
}

class WindowApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = WindowApiPigeonCodec(readerWriter: WindowApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WindowApi {
  func startDrag() throws
  func setMenuBarMode(enabled: Bool) throws
  func getMenuBarMode() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WindowApiSetup {
  static var codec: FlutterStandardMessageCodec { WindowApiPigeonCodec.shared }
  /// Sets up an instance of `WindowApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WindowApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startDragChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protonify.WindowApi.startDrag\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDragChannel.setMessageHandler { _, reply in
        do {
          try api.startDrag()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startDragChannel.setMessageHandler(nil)
    }
    let setMenuBarModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protonify.WindowApi.setMenuBarMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMenuBarModeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setMenuBarMode(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMenuBarModeChannel.setMessageHandler(nil)
    }
    let getMenuBarModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.protonify.WindowApi.getMenuBarMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMenuBarModeChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getMenuBarMode()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getMenuBarModeChannel.setMessageHandler(nil)
    }
  }
}
